<?php

return [
            [
                'type' => 'hero',
                'name' => 'home_hero',
                'sort_order' => 10,
                'title' => 'Agende e taccuini per ogni giorno',
                'subtitle' => 'CIAK Firenze',
                'content' => 'Oggetti quotidiani per scrivere, pianificare e portare con te le idee.',
                'button_label' => 'Scopri la collezione',
                'button_url' => '/catalog',
            ],
            [
                'type' => 'section_intro',
                'name' => 'home_about_intro',
                'sort_order' => 20,
                'title' => 'La nostra storia, il nostro sguardo sul futuro.',
                'subtitle' => 'Chi siamo & Vision',
                'content' => 'Ciak celebra la bellezza della carta e la trasforma in esperienze di valore. Ogni prodotto nasce da attenzione, ricerca e passione artigianale.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'about',
                'name' => 'home_about',
                'sort_order' => 30,
                'title' => 'Chi siamo',
                'subtitle' => 'La nostra storia',
                'content' => 'Dal cuore di Firenze, CIAK crea agende e taccuini pensati per accompagnare idee, progetti e giornate piene di dettagli.',
                'button_label' => 'Scopri chi siamo',
                'button_url' => '/about',
            ],
            [
                'type' => 'about_highlight',
                'name' => 'home_about_highlight_1',
                'sort_order' => 31,
                'title' => 'Laboratorio',
                'subtitle' => 'scissors',
                'content' => 'Non una fabbrica: ogni pezzo nasce in un distretto artigiano con una storia di generazioni.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'about_highlight',
                'name' => 'home_about_highlight_2',
                'sort_order' => 32,
                'title' => 'Fatto a mano',
                'subtitle' => 'hand',
                'content' => 'Materiali, copertine ed elastici passano dalle mani di artigiani che conoscono il mestiere.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'about_highlight',
                'name' => 'home_about_highlight_3',
                'sort_order' => 33,
                'title' => 'Responsabilità',
                'subtitle' => 'leaf',
                'content' => 'Scelte attente, materiali selezionati e cura dell’impatto ambientale.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'vision',
                'name' => 'home_vision',
                'sort_order' => 40,
                'title' => 'La nostra vision',
                'subtitle' => 'Vision',
                'content' => 'Crediamo in oggetti quotidiani fatti bene: essenziali, durevoli, belli da usare ogni giorno e capaci di lasciare spazio a ciò che conta.',
                'button_label' => 'Scopri la nostra vision',
                'button_url' => '/vision',
            ],
            [
                'type' => 'vision_highlight',
                'name' => 'home_vision_highlight_1',
                'sort_order' => 41,
                'title' => 'Essenzialità',
                'subtitle' => 'circle',
                'content' => 'Progetti chiari, funzionali e capaci di durare nel tempo.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'vision_highlight',
                'name' => 'home_vision_highlight_2',
                'sort_order' => 42,
                'title' => 'Durabilità',
                'subtitle' => 'shield-check',
                'content' => 'Oggetti pensati per accompagnare l’uso quotidiano.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'section_intro',
                'name' => 'home_values_intro',
                'sort_order' => 50,
                'title' => 'I nostri valori',
                'subtitle' => null,
                'content' => null,
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'value',
                'name' => 'home_value_1',
                'sort_order' => 51,
                'title' => 'Laboratorio',
                'subtitle' => 'scissors',
                'content' => 'La cura del fare e l’esperienza artigiana guidano ogni scelta.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'value',
                'name' => 'home_value_2',
                'sort_order' => 52,
                'title' => 'Artigianalità',
                'subtitle' => 'hand',
                'content' => 'Una cultura del prodotto costruita attraverso dettagli e competenze.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'value',
                'name' => 'home_value_3',
                'sort_order' => 53,
                'title' => 'Responsabilità',
                'subtitle' => 'leaf',
                'content' => 'Materiali e processi scelti con attenzione e consapevolezza.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'value',
                'name' => 'home_value_4',
                'sort_order' => 54,
                'title' => 'Made in Italy',
                'subtitle' => 'map-pin',
                'content' => 'Una filiera italiana fatta di esperienza, territorio e qualità.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'section_intro',
                'name' => 'home_featured_intro',
                'sort_order' => 60,
                'title' => 'Scelti per te',
                'subtitle' => 'In evidenza',
                'content' => null,
                'button_label' => 'Vedi tutti',
                'button_url' => '/catalog',
            ],
            [
                'type' => 'section_intro',
                'name' => 'home_formats_intro',
                'sort_order' => 70,
                'title' => 'Scegli come scrivere',
                'subtitle' => 'Trova quello giusto',
                'content' => 'Scegli il formato che segue il tuo modo di organizzare idee, impegni e progetti.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'format',
                'name' => 'home_format_daily',
                'sort_order' => 71,
                'title' => 'Agenda giornaliera',
                'subtitle' => 'Agende',
                'content' => 'Una pagina per ogni giorno: tanto spazio per pensare e per fermarsi a scrivere ciò che conta.',
                'button_label' => 'Scopri la selezione',
                'button_url' => '/catalog',
                'settings' => [
                    'specs' => [
                        'it' => ['Cinque lingue: EN-FR-DE-ES-IT', 'Orario', 'Ampio spazio per scrivere'],
                        'en' => ['Five languages: EN-FR-DE-ES-IT', 'Time schedule', 'Ample writing space'],
                    ],
                ],
            ],
            [
                'type' => 'format',
                'name' => 'home_format_weekly',
                'sort_order' => 72,
                'title' => 'Agenda settimanale',
                'subtitle' => 'Agende',
                'content' => 'Vista di sette giorni per chi organizza la settimana prima ancora che inizi.',
                'button_label' => 'Scopri la selezione',
                'button_url' => '/catalog',
                'settings' => [
                    'specs' => [
                        'it' => ['Cinque lingue: EN-FR-DE-ES-IT', 'Settimana in due pagine', 'Calendario'],
                        'en' => ['Five languages: EN-FR-DE-ES-IT', 'Week on two pages', 'Calendar'],
                    ],
                ],
            ],
            [
                'type' => 'format',
                'name' => 'home_format_dotted',
                'sort_order' => 73,
                'title' => 'Pagine a puntini',
                'subtitle' => 'Taccuini e quaderni',
                'content' => 'Una griglia leggera che guida la scrittura: perfetta per liste, schizzi e bullet journal.',
                'button_label' => 'Scopri la selezione',
                'button_url' => '/catalog',
                'settings' => [
                    'specs' => [
                        'it' => ['Struttura flessibile', 'Libertà di scrivere', 'Per chi ama organizzarsi'],
                        'en' => ['Flexible structure', 'Freedom to write and draw', 'For the organized mind'],
                    ],
                ],
            ],
            [
                'type' => 'format',
                'name' => 'home_format_lined',
                'sort_order' => 74,
                'title' => 'Pagine a righe',
                'subtitle' => 'Taccuini e quaderni',
                'content' => 'La pagina classica su cui scrivere: ordinata, familiare e simmetrica.',
                'button_label' => 'Scopri la selezione',
                'button_url' => '/catalog',
                'settings' => [
                    'specs' => [
                        'it' => ['Scrittura ordinata', 'Nessuna distrazione', 'Adatta a testi lunghi'],
                        'en' => ['Neat handwriting', 'No distractions', 'Great for longer notes'],
                    ],
                ],
            ],
            [
                'type' => 'format',
                'name' => 'home_format_blank',
                'sort_order' => 75,
                'title' => 'Pagine bianche',
                'subtitle' => 'Taccuini e quaderni',
                'content' => 'Nessuna riga, nessun limite: solo spazio bianco per idee, disegni e pensieri che non seguono uno schema predefinito.',
                'button_label' => 'Scopri la selezione',
                'button_url' => '/catalog',
                'settings' => [
                    'specs' => [
                        'it' => ['Nessun limite', 'Spazio versatile', 'Massima libertà'],
                        'en' => ['No limits', 'Versatile space', 'Total freedom'],
                    ],
                ],
            ],
            [
                'type' => 'editorial',
                'name' => 'home_story',
                'sort_order' => 80,
                'title' => 'Carta, colore e dettagli essenziali',
                'subtitle' => 'Dettagli CIAK',
                'content' => 'Usa questo slot per un’immagine ambientata caricata dal back office.',
                'button_label' => null,
                'button_url' => null,
            ],
            [
                'type' => 'editorial_banner',
                'name' => 'home_banner',
                'sort_order' => 90,
                'title' => 'Pensati per accompagnare lavoro, studio e viaggio',
                'subtitle' => 'Collezioni',
                'content' => 'Uno spazio flessibile per campagne, stagionalità o nuovi lanci.',
                'button_label' => 'Vai allo shop',
                'button_url' => '/catalog',
            ],
            [
                'type' => 'instagram_gallery',
                'name' => 'home_instagram',
                'sort_order' => 100,
                'title' => 'CIAK su Instagram',
                'subtitle' => 'Social',
                'content' => 'Ispirazioni, colori e dettagli dalle ultime storie del nostro mondo.',
                'button_label' => 'Apri Instagram',
                'button_url' => 'https://www.instagram.com/ciak_firenze/',
            ],
        ];;
