<?php

return [
    [
        'type' => 'hero',
        'name' => 'home_hero',
        'sort_order' => 10,
        'title' => 'Plein Air',
        'subtitle' => 'Ready',
        'content' => 'Vivi l\'outdoor senza pensieri',
        'button_label' => 'Acquista ora',
        'button_url' => '/catalog',
    ],
    [
        'type' => 'about',
        'name' => 'home_about',
        'sort_order' => 20,
        'title' => 'Accessori per la tua vita in movimento',
        'subtitle' => 'Be smart, be ready',
        'content' => 'Se sei sempre in movimento, hai bisogno di accessori che siano pronti quanto te. Ready è il brand di accessori smart e funzionali, progettati per semplificarti la vita, senza rinunciare allo stile.',
        'button_label' => 'Scopri Ready',
        'button_url' => '/about',
    ],
    [
        'type' => 'section_intro',
        'name' => 'home_featured_intro',
        'sort_order' => 30,
        'title' => 'Be smart, be ready',
        'subtitle' => 'Prodotti Ready',
        'content' => null,
        'button_label' => null,
        'button_url' => null,
    ],
    [
        'type' => 'visual_collection',
        'name' => 'home_ready_collection_1',
        'sort_order' => 40,
        'title' => 'Plein Air',
        'subtitle' => 'Visualizza la collezione',
        'image_path' => 'https://ready-to.it/wp-content/uploads/2026/06/immagine_pleinair-800x800.jpg',
        'button_label' => 'Visualizza la collezione',
        'button_url' => null,
        'settings' => ['category_terms' => ['plein', 'outdoor', 'antipioggia']],
    ],
    [
        'type' => 'visual_collection',
        'name' => 'home_ready_collection_2',
        'sort_order' => 41,
        'title' => 'Fruggy',
        'subtitle' => 'Visualizza la collezione',
        'image_path' => 'https://ready-to.it/wp-content/uploads/2025/05/ready-to-banner-home-box-800x800.jpg',
        'button_label' => 'Visualizza la collezione',
        'button_url' => null,
        'settings' => ['category_terms' => ['fruggy', 'shopper']],
    ],
    [
        'type' => 'visual_collection',
        'name' => 'home_ready_collection_3',
        'sort_order' => 42,
        'title' => 'Light',
        'subtitle' => 'Visualizza la collezione',
        'image_path' => 'https://ready-to.it/wp-content/uploads/2026/06/immagine_light-800x800.jpg',
        'button_label' => 'Visualizza la collezione',
        'button_url' => null,
        'settings' => ['category_terms' => ['light', 'ombrello', 'poncho']],
    ],
    [
        'type' => 'visual_collection',
        'name' => 'home_ready_collection_4',
        'sort_order' => 43,
        'title' => 'Pattern',
        'subtitle' => 'Visualizza la collezione',
        'image_path' => 'https://ready-to.it/wp-content/uploads/2026/06/immagine_pattern-800x800.jpg',
        'button_label' => 'Visualizza la collezione',
        'button_url' => null,
        'settings' => ['category_terms' => ['pattern']],
    ],
    [
        'type' => 'editorial_banner',
        'name' => 'home_ready_spotlight',
        'sort_order' => 50,
        'title' => 'Zaino ripiegabile',
        'subtitle' => 'Best-selling',
        'content' => 'Lo zaino ripiegabile combina leggerezza, stile e praticità.',
        'image_path' => 'https://ready-to.it/wp-content/uploads/2025/05/ready-to-banner-home-everyday-800x800.jpg',
        'button_label' => 'Scopri di più',
        'button_url' => null,
        'settings' => ['category_terms' => ['zaini', 'zaino', 'everyday']],
    ],
    [
        'type' => 'newsletter',
        'name' => 'home_ready_newsletter',
        'sort_order' => 60,
        'title' => 'Newsletter',
        'subtitle' => 'Rimani aggiornato',
        'content' => 'Rimani aggiornato sulle novità, promozioni e nuovi arrivi.',
        'button_label' => 'Iscriviti',
        'button_url' => null,
    ],
    [
        'type' => 'instagram_gallery',
        'name' => 'home_instagram',
        'sort_order' => 70,
        'title' => 'Segui il mondo Ready',
        'subtitle' => 'Su Instagram',
        'content' => 'Scopri prodotti, colori e novità dal mondo Ready.',
        'button_label' => '@readyofficial.it',
        'button_url' => 'https://www.instagram.com/readyofficial.it/',
    ],
];
